# Generated by Django 4.2.5 on 2023-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_info', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
