# Generated by Django 4.2.5 on 2023-09-23 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vlad', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('duration', models.TimeField(default=datetime.time(1, 2, 3))),
                ('description', models.TextField(default='<blank>')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='film_photos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmcatalog.author')),
                ('genre', models.ManyToManyField(to='filmcatalog.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
