# Generated by Django 4.2.5 on 2023-11-18 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmcatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 11, 18, 22, 2, 17, 6655))),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
