# Generated by Django 4.2.5 on 2023-11-18 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmcatalog', '0009_alter_countdown_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
