# Generated by Django 4.2.5 on 2023-11-19 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmcatalog', '0012_alter_countdown_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 19, 31, 44, 938668)),
        ),
    ]
